name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "armv7-unknown-linux-gnueabihf"
      - name: Build
        run: cargo build --target armv7-unknown-linux-gnueabihf --release
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          tag: latest
          assets: '*'
          fail-if-no-release: false
          fail-if-no-assets: false
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Latest
          body: >
            This release is automatically updated by a Github Action on every push to the main branch.
          tag_name: latest
          generate_release_notes: false
          files: |
            target/armv7-unknown-linux-gnueabihf/release/espeak-web
